# Header
menu:
  GIT: /git
  WEB: /web
  SVN: /svn
  proxy: /proxy
  归档: /archives
  关于: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
# - tag
- tagcloud
- archive

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: